import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Separator } from '@/components/ui/separator';
import { FileText, Download, Eye, Share2, BarChart3, Users, Target } from 'lucide-react';

export const PitchDeckGenerator = () => {
  const deckStatus = {
    completion: 85,
    lastUpdated: '2 hours ago',
    totalSlides: 14,
    readySlides: 12
  };

  const slideTemplates = [
    { id: 1, title: 'Problem Statement', status: 'completed', autoGenerated: true },
    { id: 2, title: 'Solution Overview', status: 'completed', autoGenerated: true },
    { id: 3, title: 'Market Size & Opportunity', status: 'completed', autoGenerated: true },
    { id: 4, title: 'Business Model', status: 'completed', autoGenerated: true },
    { id: 5, title: 'Financial Projections', status: 'completed', autoGenerated: true },
    { id: 6, title: 'Revenue Model', status: 'completed', autoGenerated: true },
    { id: 7, title: 'Competitive Analysis', status: 'completed', autoGenerated: true },
    { id: 8, title: 'Team Overview', status: 'in-progress', autoGenerated: false },
    { id: 9, title: 'Traction & Metrics', status: 'completed', autoGenerated: true },
    { id: 10, title: 'Go-to-Market Strategy', status: 'completed', autoGenerated: true },
    { id: 11, title: 'Funding Requirements', status: 'completed', autoGenerated: true },
    { id: 12, title: 'Use of Funds', status: 'completed', autoGenerated: true },
    { id: 13, title: 'Key Milestones', status: 'in-progress', autoGenerated: false },
    { id: 14, title: 'Contact & Next Steps', status: 'pending', autoGenerated: false }
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed':
        return 'bg-success text-success-foreground';
      case 'in-progress':
        return 'bg-warning text-warning-foreground';
      case 'pending':
        return 'bg-muted text-muted-foreground';
      default:
        return 'bg-muted text-muted-foreground';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed':
        return '✅';
      case 'in-progress':
        return '🔄';
      case 'pending':
        return '⏳';
      default:
        return '📄';
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">VC Pitch Deck Generator</h1>
          <p className="text-muted-foreground mt-1">AI-powered investor-ready financial presentations</p>
        </div>
        <div className="flex items-center space-x-3">
          <Button variant="outline">
            <Eye className="w-4 h-4 mr-2" />
            Preview
          </Button>
          <Button variant="outline">
            <Share2 className="w-4 h-4 mr-2" />
            Share
          </Button>
          <Button className="bg-gradient-primary">
            <Download className="w-4 h-4 mr-2" />
            Export PDF
          </Button>
        </div>
      </div>

      {/* Deck Status */}
      <Card className="shadow-card">
        <CardContent className="p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-gradient-primary rounded-lg flex items-center justify-center">
                <FileText className="w-6 h-6 text-primary-foreground" />
              </div>
              <div>
                <h3 className="font-semibold">Series A Pitch Deck</h3>
                <p className="text-sm text-muted-foreground">Last updated: {deckStatus.lastUpdated}</p>
              </div>
            </div>
            <Badge className="bg-primary text-primary-foreground">
              {deckStatus.completion}% Complete
            </Badge>
          </div>
          
          <div className="space-y-3">
            <div className="flex justify-between text-sm">
              <span>Completion Progress</span>
              <span>{deckStatus.readySlides}/{deckStatus.totalSlides} slides ready</span>
            </div>
            <Progress value={deckStatus.completion} className="h-2" />
          </div>

          <div className="grid grid-cols-3 gap-4 mt-6 text-center">
            <div>
              <div className="text-2xl font-bold text-primary">{deckStatus.totalSlides}</div>
              <div className="text-xs text-muted-foreground">Total Slides</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-success">{deckStatus.readySlides}</div>
              <div className="text-xs text-muted-foreground">Auto-Generated</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-warning">2</div>
              <div className="text-xs text-muted-foreground">Need Input</div>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Slide Templates */}
        <Card className="shadow-card">
          <CardHeader>
            <CardTitle>Slide Templates</CardTitle>
            <CardDescription>AI-generated slides from your financial data</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3 max-h-96 overflow-y-auto">
              {slideTemplates.map((slide) => (
                <div key={slide.id} className="flex items-center justify-between p-3 bg-muted rounded-lg">
                  <div className="flex items-center space-x-3">
                    <span className="text-lg">{getStatusIcon(slide.status)}</span>
                    <div>
                      <div className="font-medium text-sm">{slide.title}</div>
                      <div className="text-xs text-muted-foreground">
                        {slide.autoGenerated ? 'Auto-generated' : 'Manual input required'}
                      </div>
                    </div>
                  </div>
                  <Badge className={getStatusColor(slide.status)}>
                    {slide.status}
                  </Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Key Metrics Preview */}
        <Card className="shadow-card">
          <CardHeader>
            <CardTitle>Key Financial Slides Preview</CardTitle>
            <CardDescription>Auto-generated from your business data</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-4 bg-gradient-card rounded-lg">
              <div className="flex items-center space-x-2 mb-2">
                <BarChart3 className="w-4 h-4 text-primary" />
                <span className="font-medium">Financial Projections</span>
              </div>
              <div className="text-sm text-muted-foreground">
                3-year revenue forecast: £150k → £1.2M ARR
              </div>
              <div className="text-sm text-muted-foreground">
                Break-even: Month 14, 68% gross margin
              </div>
            </div>

            <div className="p-4 bg-gradient-card rounded-lg">
              <div className="flex items-center space-x-2 mb-2">
                <Target className="w-4 h-4 text-success" />
                <span className="font-medium">Funding Requirements</span>
              </div>
              <div className="text-sm text-muted-foreground">
                Seeking: £500k Series A
              </div>
              <div className="text-sm text-muted-foreground">
                18-month runway to profitability
              </div>
            </div>

            <div className="p-4 bg-gradient-card rounded-lg">
              <div className="flex items-center space-x-2 mb-2">
                <Users className="w-4 h-4 text-accent" />
                <span className="font-medium">Market Opportunity</span>
              </div>
              <div className="text-sm text-muted-foreground">
                TAM: £2.1B, Growing at 23% CAGR
              </div>
              <div className="text-sm text-muted-foreground">
                Target: 0.1% market capture
              </div>
            </div>

            <Separator />

            <div className="text-center">
              <Button className="w-full">
                <Eye className="w-4 h-4 mr-2" />
                Preview Full Deck
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* AI Generation Info */}
      <Card className="shadow-card bg-gradient-card">
        <CardHeader>
          <CardTitle>AI Pitch Deck Intelligence</CardTitle>
          <CardDescription>How your deck is automatically generated</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="text-center p-4">
              <div className="w-12 h-12 bg-primary rounded-lg flex items-center justify-center mx-auto mb-3">
                <BarChart3 className="w-6 h-6 text-primary-foreground" />
              </div>
              <h4 className="font-medium mb-1">Financial Data</h4>
              <p className="text-xs text-muted-foreground">Automatically pulls from your tax planning, cash flow, and profitability forecasts</p>
            </div>
            <div className="text-center p-4">
              <div className="w-12 h-12 bg-success rounded-lg flex items-center justify-center mx-auto mb-3">
                <Target className="w-6 h-6 text-success-foreground" />
              </div>
              <h4 className="font-medium mb-1">Market Intelligence</h4>
              <p className="text-xs text-muted-foreground">Integrates real-time market data from Bloomberg, FT, and industry reports</p>
            </div>
            <div className="text-center p-4">
              <div className="w-12 h-12 bg-accent rounded-lg flex items-center justify-center mx-auto mb-3">
                <FileText className="w-6 h-6 text-accent-foreground" />
              </div>
              <h4 className="font-medium mb-1">Investor Standards</h4>
              <p className="text-xs text-muted-foreground">Templates optimized for UK Series A standards and investor expectations</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};